{% set name = "seawater" %}
{% set version = "3.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/seawater-{{ version }}.tar.gz
  sha256: ed3443330d76e5054ad6e3f60ac5a1e407f703504887be9352c35a9d77fd6fa8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.8
    - numpy
    - scipy

test:
  imports:
    - seawater
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyoceans/python-seawater
  summary: Seawater Library for Python
  license: MIT AND LicenseRef-CSIRO
  license_file:
    - LICENSE.txt
    - LICENSE.CSIRO

extra:
  recipe-maintainers:
    - ocefpaf
