{% set version = "3.3.4" %}

package:
  name: seawater
  version: {{ version }}

source:
  fn: seawater-{{ version }}.tar.gz
  url: https://github.com/pyoceans/python-seawater/archive/v{{ version }}.tar.gz
  sha256: 8fecf37d69fbe5f2bf50855aab38f9438b44ee4195e925edfa9e544f75cfecc8

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy

test:
  imports:
    - seawater

about:
  home: https://github.com/pyoceans/python-seawater
  license: MIT
  summary: 'Seawater Library for Python.'

extra:
  recipe-maintainers:
    - ocefpaf
