travis:
  secure:
    BINSTAR_TOKEN: ifyc8abL2jIOK59unPu/m5mKkFOShoXZGTGXpdcKDQil87iiWulfnDHhyQz2QD32rc11PfxVBI7GLjm/Kex5+Myz/iRlAws/O+9D7py4bpVOnX2+iFIaJQZWZvfD40G+bgNHT01vqS+mWtaEmvyioM2OLLK2KadW8XXOsnORiGU5t+0zqTnjcaiZH8n09u378hW0BsZPKEvHw5ZevvzWDQK8ups5xxNLfrJFCOh0DGFAtjGBgMfjzNtkgUFUlE/URwWIKTfthkN+jYLZbIrZay3qsz/qgLVDXtodNgSgdxJxb0n409GJg22JoYBsZTMr7wxlJ2WAhuIKq3ZqrTmZxss1oOh3FfsOGFAMT3uOgAulInjN5n366c66rpo0MRwNYkmaw7pUdsoZ1jQmrMm8VA2JeYdBE2PgeFEUKELstty22yqO1HDdAVR6PVQ63lavKibPxJAga0a27zZqONcagxfRlUz7l6rR8HbYSN9xQeWmR5tXpAdm9SuIqjOvt0wmjSProkZdaYWyf5FINDbVbHT5v8uKR78xD1vZymOW9ZlxyauZGUctHge62vN0XAELQmTvY58lPm65JTytNYshaiVXCYoJBqGG4EzH1hyHSr6pJsZ+D7d0d1x/uUHIs3MDQLLrOO7PLZneeXxoLIy6e+lERxBznlTAmrVtBgolPHI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
