travis:
  secure:
    BINSTAR_TOKEN: Hhhh7cGf91V1LReV5DHMGI9SPx4CPPkZ7LdBBTg09SBboKh1cGxe/fYa7+utaXnVNgt1aDUitYQbVbB8sMM2Cc1iQlvsD9jxba8TfjsIRHc7ATeiifwlyX5anaKYOQ92/Za89m0f9scFwFJ/oVIhCsI7FsfydeQXsjUSVHwfHlrXB6N+5S46N2lhbSylScwmpOiB8UJ4Bi/n3VqvM7+xdC4rpI+lwFUOyx7ep95K5SQtpDK1WPw8qr3Tfu+RKq+wD+WgLP2SurLTlFCbrZM4GK4rwuC8u3hEQO/Jb8Q3mengeYDj75TbufB/T3S5r3M/PA7VmJADIkSEfpO5Gn+2xjLW+mpYvlJBn5xykJhxZuVWEs5T+VvzLOPLZFznlFELhKNckPzDSRKW/2E/i/u9HNvd9Bn+lY1qLtlaPKcJmKr1yDUZgPvBifz/vFtKlqMZ/xHnhCupujbmjhm8YiGWenspolPjlPeFozvbJ4q07vM6j+svfxR2TkOx7Kb7djAZZtSQlEamJlNlQFv4TwxOGSogH8r7qMHu6iJxguwSF99SUeG4DoDfrjVKkNxrRaNM6RE4qCGQ6nMmuxNH21iWgX5aUln9+Te04TcbOOK2ZQZpiLjh1F1AcgMliGnHGFdFm5qWlLR5j+YAf2N5JahK7PiniH841rsFPQ29zGwCSzA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
